# Generated by Django 2.1.15 on 2023-12-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gogreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gogreen.Plants'),
        ),
    ]
