# Generated by Django 2.1.15 on 2023-12-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogreen', '0002_order_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='cost',
            field=models.IntegerField(unique=True),
        ),
    ]
