# Generated by Django 2.1.15 on 2023-12-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gogreen', '0003_auto_20231210_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_cost', to='gogreen.Plants', to_field='cost'),
        ),
    ]
