# Generated by Django 2.1.15 on 2023-12-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogreen', '0005_auto_20231210_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(),
        ),
    ]
