# Generated by Django 2.1.15 on 2023-12-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogreen', '0006_auto_20231210_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
