# Generated by Django 2.1.15 on 2023-12-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogreen', '0007_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plant',
        ),
        migrations.AddField(
            model_name='order',
            name='plants',
            field=models.ManyToManyField(to='gogreen.Plants'),
        ),
    ]
