# Generated by Django 2.1.15 on 2023-12-11 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gogreen', '0008_auto_20231211_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plants',
            name='seller',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
